### ISSUE TITLE
Deprecated function: Return type of Andileco\Util\EvalMath\MethodsRegistry::offsetExists($offset) 

### ISSUE THREAD

**Issue by heyyo-droid** [andileco/eval-math#2]
Deprecated function: Return type of Andileco\Util\EvalMath\MethodsRegistry::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 16 of /var/www/html/vendor/andileco/eval-math/src/MethodsRegistry.php).
include('/var/www/html/vendor/andileco/eval-math/src/MethodsRegistry.php') (Line: 571)

**Comment by andileco** [comment]
Closing this, as it's been addressed by the referenced issues.
